# GitHub workflow to implement CICD for Terraform code to deploy infrastructure in Azure
name: Terraform code CICD for infrastructure deployment

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read
  id-token: write

env:
  TERRAFORM_VERSION: 1.14.0
  TERRAFORM_WORKDIR: terraform

jobs:
  # Build and Deploy Job
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} # this is the default subscription that will be used by Terraform, you can also configure multiple providers in Terraform code to use different subscriptions

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.TERRAFORM_WORKDIR }}

      - name: Terraform Plan
        run: terraform plan
        working-directory: ${{ env.TERRAFORM_WORKDIR }}

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: terraform apply -auto-approve
        working-directory: ${{ env.TERRAFORM_WORKDIR }}

      - name: Terraform Destroy
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: terraform destroy -auto-approve
        working-directory: ${{ env.TERRAFORM_WORKDIR }}
